region = "us-east-1"
image = "zipofar/terraform_dbp_learn:latest"
instance_key_file = "ssh_keys/id_rsa_instance_key.pub"
instance_ami = "ami-09e2e5104f310ffb5"
instance_user = "core"
env = "id_rsa_instance_key"
